### PR TITLE
Upgrade jsdoc(api) and fix tests

### LINKED ISSUE #101: Tests failing
This library is generating types for Ubers `h3-js` bindings which I depend on. But the generated types for generics are looking strange.

 * `T[]` becomes `[ 'Array' ]<T>`
 * `Array<T>` becomes `[ 'Array' ]<T>`
 * `Promise<T>` becomes `[ 'Promise' ]<T>`

Tests in this repo are failing on a fresh clone as well.

I've tried figuring out if it was a recent commit or a backwards-incompatible dependency update but I'm unable to figure out the cause. If I could be pointed in the right direction I'll try and submit a PR.

### PR DESCRIPTION
**Pull request by zachasme**
Resolves #101.

There was an issue with type applications in Node 12 which was fixed in [this commit to jsdoc](https://github.com/jsdoc/jsdoc/commit/dc9d5afe72a3039137e7a49c311473ed25e78445).

This PR upgrades `jsdoc` and `jsdoc-api`. However, this `jsdoc` upgrade introduces some changes to the output:
 * Most of the Closure Compiler tags were added to the list of definitions at some point, but in such a way that the are ignored. I've added a simple plugin which adds `@template` to the list of tags in jsdoc output. This means users need to use a similar plugin to achieve `@template` support. There might a better solution.
 * Classes and constructors are being merged in strange ways and `@class` tags without a name results in the class being considered `undocumented` which in turn means it gets deleted due to `data({ undocumented: true }).remove();` in `publish.ts`. I've added names to fixtures and expected to avoid the problem, but it would be preferable to find a better solution.
 * Probably related to the previous point, private constructors meant the class became `undocumented`, so I've changed the test using `@private` to `@hideconstructor`.

Most of these should probably be brought up as issues in jsdoc.

### CODE REVIEW

File: test/lib/plugin.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+exports.defineTags = function(dictionary) {
+    dictionary.defineTag("template", {
+        onTagged: function(doclet, tag) {
+            doclet.tags = doclet.tags || [];
+            doclet.tags.push(tag);
```
Comment (englercj) [inline test/lib/plugin.js]: I think the real fix here is to use the new output jsdoc produces for `@template` rather than hack it back into the "unknown tags" list.
