### PR TITLE
resolves #113 Added source location information to warnings

### LINKED ISSUE #113: Add source location to error output
It would be rather useful if the error messages actually pointed to the source file, line, and column where the problematic JSDoc appeared.

```
[TSD-JSDoc] dataset.js:619:4 Failed to find parent of doclet 'DatasetLocal#_getItemIndexes' using memberof 'DatasetLocal', this is likely due to invalid JSDoc.
[TSD-JSDoc] dataset.js:630:4 Failed to find parent of doclet 'DatasetLocal#_readAndParseFile' using memberof 'DatasetLocal', this is likely due to invalid JSDoc.
[TSD-JSDoc] stealth.js:40:0 Failed to find parent of doclet 'module.exports' using memberof 'module', this is likely due to invalid JSDoc.
[TSD-JSDoc] autoscaled_pool.js:209:4 Unable to resolve type for AutoscaledPool#minConcurrency, none specified in JSDoc. Defaulting to `any`.
```

### PR DESCRIPTION
**Pull request by yin**
The error messages are missing source locations for ease of navigating. This PR add to every logged error: Source filename (not the path), line number, and column number:

```
[TSD-JSDoc] dataset.js:619:4 Failed to find parent of doclet 'DatasetLocal#_getItemIndexes' using memberof 'DatasetLocal', this is likely due to invalid JSDoc.
[TSD-JSDoc] dataset.js:630:4 Failed to find parent of doclet 'DatasetLocal#_readAndParseFile' using memberof 'DatasetLocal', this is likely due to invalid JSDoc.
[TSD-JSDoc] stealth.js:40:0 Failed to find parent of doclet 'module.exports' using memberof 'module', this is likely due to invalid JSDoc.
[TSD-JSDoc] autoscaled_pool.js:209:4 Unable to resolve type for AutoscaledPool#minConcurrency, none specified in JSDoc. Defaulting to `any`.
```

Please review and comment.

### CODE REVIEW

File: src/logger.ts [hunk 1]
```diff
@@ -7,12 +7,19 @@ export function setVerbose(value: boolean)
     isVerbose = value;
 }
 
-export function warn(msg: string, data?: any)
+export function warn(msg: string, data?: any|TAnyDoclet)
```
Comment (englercj) [inline src/logger.ts]:
```suggestion
export function warn(msg: string, data?: any)
```

No need for the extra type there.

File: src/logger.ts [hunk 2]
```diff
@@ -7,12 +7,19 @@ export function setVerbose(value: boolean)
...
 {
+
```
Comment (englercj) [inline src/logger.ts]:
```suggestion
```

Extra newline got added.

File: src/logger.ts [hunk 3]
```diff
@@ -7,12 +7,19 @@ export function setVerbose(value: boolean)
...
     if (typeof(console) === 'undefined')
         return;
 
-    console.warn(`${header} ${msg}`);
+    let prefix = header;
+    if (arguments.length > 1 && data && data.hasOwnProperty('meta')) {
```
Comment (englercj) [inline src/logger.ts]:
```suggestion
    if (data && data.meta)
    {
```

Don't need to check `arguments.length` and `hasOwnProperty` is overkill here.

**Comment by yin** [comment]
I fully agree.
