### PR TITLE
resolves #108 generate dtslint compliant code

### LINKED ISSUE #108: Make the generated file compliant with dtslint
Here's a simple example:

```js
/**
 * @class Foo
 */
class Foo {
  /**
   * @returns {string} - The {string} bar
   */
  bar() {
    return 'bar'
  }
}
```
And here's the generated file:

**types.d.ts**
```typescript
/**
 * @class Foo
 */
declare class Foo {
    /**
     * @returns {string} - The {string} bar
     */
    bar(): string;
}


```

Using [dtslint](https://github.com/microsoft/dtslint):

```console
$ dtslint types
Error: /path/to/types/types.d.ts:2:5
ERROR: 2:5   no-redundant-jsdoc          JSDoc tag '@class' is redundant in TypeScript code.
ERROR: 6:17  no-redundant-jsdoc          Type annotation in JSDoc is redundant in TypeScript code.
ERROR: 10:1  trim-file                   File should not end with a blank line. (Ending in one newline OK, ending in two newlines not OK.) See: https://github.com/Microsoft/dtslint/blob/master/docs/trim-file.md
ERROR: 11:1  no-consecutive-blank-lines  Consecutive blank lines are forbidden
```

As you can see we should do the following:

- [ ] Remove redundant jsdoc tags `@class`, `@namespace`...
- [ ] Remove type annotation `{string}`
- [ ] Trim lines

And here's the expected result:

**types.d.ts**
```typescript
/**
 */
declare class Foo {
    /**
     * @returns The {string} bar
     */
    bar(): string;
}
```

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

File: src/create_helpers.ts [hunk 1]
```diff
@@ -67,24 +67,89 @@ function validateModuleChildren(children?: ts.Node[])
...
+                    name = `[${prop.name}]`;
+                }
+            } else {
+                name = prop.name;
+            }
+            const description = ` - ${formatMultilineComment(prop.description)}`;
+            return `\n * @${jsdocTagName} ${name}${description}`
+        }
+        return ''
+    }).filter(value => value !== '')
```
Comment (englercj) [inline src/create_helpers.ts]: I'd just do the `join('')` here since all usages of this function do it later anyway. Should make the combining string later more readable to skip the join.

Comment (Mogztter) [reply src/create_helpers.ts]: Good point, I fixed it.

**Comment by Mogztter** [comment]
> Generally looks good to me. If you could please match the coding style that exists currently that would be great. Most noticeable is the different brace style and missing parens for arrow function params.

Should be better now :wink:

File: src/create_helpers.ts [hunk 2]
```diff
@@ -67,83 +67,108 @@ function validateModuleChildren(children?: ts.Node[])
...
             description = `\n * ${formatMultilineComment((doclet['classdesc'] as string))}`;
         }
         const examples = handleExamplesComment(doclet);
         const properties = handlePropertiesComment(doclet);
         const params = handleParamsComment(doclet);
         const returns = handleReturnsComment(doclet);
 
-        if (description || examples.length > 0 || properties.length > 0 || params.length > 0 || returns.length > 0) {
-            let comment = `*${description}${examples.join('')}${properties.join('')}${params.join('')}${returns.join('')}
+        if (description || examples.length > 0 || properties.length > 0 || params.length > 0 || returns.length > 0)
```
Comment (englercj) [inline src/create_helpers.ts]: The `.length > 0` part can be removed now that it is a string since empty strings are falsey.

```
if (description || examples || properties || params || returns)
```

File: src/create_helpers.ts [hunk 3]
```diff
@@ -67,24 +67,114 @@ function validateModuleChildren(children?: ts.Node[])
...
+        {
+            description = `\n * ${formatMultilineComment((doclet['classdesc'] as string))}`;
+        }
+        const examples = handleExamplesComment(doclet);
+        const properties = handlePropertiesComment(doclet);
+        const params = handleParamsComment(doclet);
+        const returns = handleReturnsComment(doclet);
 
-        const kind = ts.SyntaxKind.MultiLineCommentTrivia;
+        if (description || examples.length > 0 || properties.length > 0 || params.length > 0 || returns.length > 0)
```
Comment (Mogztter) [inline src/create_helpers.ts]:
```suggestion
        if (description || examples || properties || params || returns)
```

**Comment by englercj** [comment]
Thanks for the changes! Looks like it just needs an update from master and it is good to go.
